/**
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.8.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * FundingRate.h
 *
 * Get the last funding Rate
 */

#ifndef IO_SWAGGER_CLIENT_MODEL_FundingRate_H_
#define IO_SWAGGER_CLIENT_MODEL_FundingRate_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// Get the last funding Rate
/// </summary>
class  FundingRate
    : public ModelBase
{
public:
    FundingRate();
    virtual ~FundingRate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FundingRate members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSymbol() const;
    bool symbolIsSet() const;
    void unsetSymbol();
    void setSymbol(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFundingRate() const;
    bool fundingRateIsSet() const;
    void unsetFunding_rate();
    void setFundingRate(utility::string_t value);
    /// <summary>
    /// 
    /// </summary>
    double getFundingRateTimestamp() const;
    bool fundingRateTimestampIsSet() const;
    void unsetFunding_rate_timestamp();
    void setFundingRateTimestamp(double value);

protected:
    utility::string_t m_Symbol;
    bool m_SymbolIsSet;
    utility::string_t m_Funding_rate;
    bool m_Funding_rateIsSet;
    double m_Funding_rate_timestamp;
    bool m_Funding_rate_timestampIsSet;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_MODEL_FundingRate_H_ */
