/**
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BybitApi) {
      root.BybitApi = {};
    }
    root.BybitApi.LinearSwitchModeResult = factory(root.BybitApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The LinearSwitchModeResult model module.
   * @module model/LinearSwitchModeResult
   * @version 0.2.10
   */

  /**
   * Constructs a new <code>LinearSwitchModeResult</code>.
   * @alias module:model/LinearSwitchModeResult
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>LinearSwitchModeResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LinearSwitchModeResult} obj Optional instance to populate.
   * @return {module:model/LinearSwitchModeResult} The populated <code>LinearSwitchModeResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('tp_sl_mode')) {
        obj['tp_sl_mode'] = ApiClient.convertToType(data['tp_sl_mode'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} tp_sl_mode
   */
  exports.prototype['tp_sl_mode'] = undefined;



  return exports;
}));


