/*
 * Bybit API
 * ## REST API for the Bybit Exchange. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConditionalApi
 */
@Ignore
public class ConditionalApiTest {

    private final ConditionalApi api = new ConditionalApi();

    
    /**
     * Cancel conditional order.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void conditionalCancelTest() throws ApiException {
        String stopOrderId = null;
        Object response = api.conditionalCancel(stopOrderId);

        // TODO: test validations
    }
    
    /**
     * Get my conditional order list.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void conditionalGetOrdersTest() throws ApiException {
        String stopOrderId = null;
        String orderLinkId = null;
        String symbol = null;
        String order = null;
        BigDecimal page = null;
        BigDecimal limit = null;
        Object response = api.conditionalGetOrders(stopOrderId, orderLinkId, symbol, order, page, limit);

        // TODO: test validations
    }
    
    /**
     * Place a new conditional order.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void conditionalNewTest() throws ApiException {
        String side = null;
        String symbol = null;
        String orderType = null;
        BigDecimal qty = null;
        Double price = null;
        Double basePrice = null;
        Double stopPx = null;
        String timeInForce = null;
        Boolean closeOnTrigger = null;
        String orderLinkId = null;
        Object response = api.conditionalNew(side, symbol, orderType, qty, price, basePrice, stopPx, timeInForce, closeOnTrigger, orderLinkId);

        // TODO: test validations
    }
    
}
