/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api-testnet.bybit.com]  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MarketApi
 */
@Ignore
public class MarketApiTest {

    private final MarketApi api = new MarketApi();

    
    /**
     * Get the orderbook.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void marketOrderbookTest() throws ApiException {
        String symbol = null;
        Object response = api.marketOrderbook(symbol);

        // TODO: test validations
    }
    
    /**
     * Get the latest information for symbol.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void marketSymbolInfoTest() throws ApiException {
        String symbol = null;
        Object response = api.marketSymbolInfo(symbol);

        // TODO: test validations
    }
    
}
