/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.12
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;
import com.alibaba.fastjson.JSON;
import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import org.junit.BeforeClass;
import org.junit.Test;

/**
 * API tests for PositionsApi
 */

public class PositionsApiTest {
    private final static PositionsApi api = new PositionsApi();

    @BeforeClass
    public static void setUp() {
        // overwrite apiClient here
         ApiClient apiClient = new ApiClient();
         apiClient.setBasePath("https://api.bybit.com"); // https://api-testnet.bybit.com
         apiClient.setApiKey("Your Apikey");
         apiClient.setSecret("Your Secret");
         api.setApiClient(apiClient);
    }

    
    /**
     * Update margin.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void positionsChangeMarginTest() throws ApiException {
        String symbol = null;
        String margin = null;
        Object response = api.positionsChangeMargin(symbol, margin);

        // TODO: test validations
    }
    
    /**
     * Get user&#39;s closed profit and loss records
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void positionsClosePnlRecordsTest() throws ApiException {
        String symbol = null;
        Integer startTime = null;
        Integer endTime = null;
        String execType = null;
        Integer page = null;
        Integer limit = null;
        Object response = api.positionsClosePnlRecords(symbol, startTime, endTime, execType, page, limit);

        // TODO: test validations
    }
    
    /**
     * Get my position list.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void positionsMyPositionTest() throws ApiException {
        String symbol = "BTCUSD";
        Object response = api.positionsMyPosition(symbol);
        System.out.println("Create order ——->>>>>>> result= " + JSON.toJSON(response).toString());

        // TODO: test validations
    }
    
    /**
     * Change user leverage.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void positionsSaveLeverageTest() throws ApiException {
        String symbol = null;
        String leverage = null;
        Object response = api.positionsSaveLeverage(symbol, leverage);

        // TODO: test validations
    }
    
    /**
     * Set Trading-Stop Condition.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void positionsTradingStopTest() throws ApiException {
        String symbol = null;
        String takeProfit = null;
        String stopLoss = null;
        String trailingStop = null;
        String newTrailingActive = null;
        Object response = api.positionsTradingStop(symbol, takeProfit, stopLoss, trailingStop, newTrailingActive);

        // TODO: test validations
    }
    
}
