/**
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model


case class RiskIDRes (
  id: Option[Number] = None,
  coin: Option[String] = None,
  limit: Option[Number] = None,
  maintainMargin: Option[String] = None,
  startingMargin: Option[String] = None,
  section: Option[String] = None,
  isLowestRisk: Option[Number] = None,
  createdAt: Option[String] = None,
  updatedAt: Option[String] = None
)

