/**
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LinearSwitchModeResult {
  
  @SerializedName("tp_sl_mode")
  private Double tpSlMode = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getTpSlMode() {
    return tpSlMode;
  }
  public void setTpSlMode(Double tpSlMode) {
    this.tpSlMode = tpSlMode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinearSwitchModeResult linearSwitchModeResult = (LinearSwitchModeResult) o;
    return (this.tpSlMode == null ? linearSwitchModeResult.tpSlMode == null : this.tpSlMode.equals(linearSwitchModeResult.tpSlMode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tpSlMode == null ? 0: this.tpSlMode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinearSwitchModeResult {\n");
    
    sb.append("  tpSlMode: ").append(tpSlMode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
