/**
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Create Linear Stop Order
 **/
@ApiModel(description = "Create Linear Stop Order")
public class LinearCreateStopOrderResult {
  
  @SerializedName("stop_order_id")
  private String stopOrderId = null;
  @SerializedName("user_id")
  private Long userId = null;
  @SerializedName("side")
  private String side = null;
  @SerializedName("symbol")
  private String symbol = null;
  @SerializedName("order_type")
  private String orderType = null;
  @SerializedName("price")
  private Double price = null;
  @SerializedName("qty")
  private Double qty = null;
  @SerializedName("time_in_force")
  private String timeInForce = null;
  @SerializedName("order_status")
  private String orderStatus = null;
  @SerializedName("trigger_price")
  private Double triggerPrice = null;
  @SerializedName("order_link_id")
  private String orderLinkId = null;
  @SerializedName("created_at")
  private String createdAt = null;
  @SerializedName("updated_at")
  private String updatedAt = null;
  @SerializedName("take_profit")
  private Double takeProfit = null;
  @SerializedName("stop_loss")
  private Double stopLoss = null;
  @SerializedName("tp_trigger_by")
  private String tpTriggerBy = null;
  @SerializedName("sl_trigger_by")
  private String slTriggerBy = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getStopOrderId() {
    return stopOrderId;
  }
  public void setStopOrderId(String stopOrderId) {
    this.stopOrderId = stopOrderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }
  public void setUserId(Long userId) {
    this.userId = userId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSide() {
    return side;
  }
  public void setSide(String side) {
    this.side = side;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSymbol() {
    return symbol;
  }
  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderType() {
    return orderType;
  }
  public void setOrderType(String orderType) {
    this.orderType = orderType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }
  public void setPrice(Double price) {
    this.price = price;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getQty() {
    return qty;
  }
  public void setQty(Double qty) {
    this.qty = qty;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTimeInForce() {
    return timeInForce;
  }
  public void setTimeInForce(String timeInForce) {
    this.timeInForce = timeInForce;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderStatus() {
    return orderStatus;
  }
  public void setOrderStatus(String orderStatus) {
    this.orderStatus = orderStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getTriggerPrice() {
    return triggerPrice;
  }
  public void setTriggerPrice(Double triggerPrice) {
    this.triggerPrice = triggerPrice;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getOrderLinkId() {
    return orderLinkId;
  }
  public void setOrderLinkId(String orderLinkId) {
    this.orderLinkId = orderLinkId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUpdatedAt() {
    return updatedAt;
  }
  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getTakeProfit() {
    return takeProfit;
  }
  public void setTakeProfit(Double takeProfit) {
    this.takeProfit = takeProfit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Double getStopLoss() {
    return stopLoss;
  }
  public void setStopLoss(Double stopLoss) {
    this.stopLoss = stopLoss;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTpTriggerBy() {
    return tpTriggerBy;
  }
  public void setTpTriggerBy(String tpTriggerBy) {
    this.tpTriggerBy = tpTriggerBy;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSlTriggerBy() {
    return slTriggerBy;
  }
  public void setSlTriggerBy(String slTriggerBy) {
    this.slTriggerBy = slTriggerBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinearCreateStopOrderResult linearCreateStopOrderResult = (LinearCreateStopOrderResult) o;
    return (this.stopOrderId == null ? linearCreateStopOrderResult.stopOrderId == null : this.stopOrderId.equals(linearCreateStopOrderResult.stopOrderId)) &&
        (this.userId == null ? linearCreateStopOrderResult.userId == null : this.userId.equals(linearCreateStopOrderResult.userId)) &&
        (this.side == null ? linearCreateStopOrderResult.side == null : this.side.equals(linearCreateStopOrderResult.side)) &&
        (this.symbol == null ? linearCreateStopOrderResult.symbol == null : this.symbol.equals(linearCreateStopOrderResult.symbol)) &&
        (this.orderType == null ? linearCreateStopOrderResult.orderType == null : this.orderType.equals(linearCreateStopOrderResult.orderType)) &&
        (this.price == null ? linearCreateStopOrderResult.price == null : this.price.equals(linearCreateStopOrderResult.price)) &&
        (this.qty == null ? linearCreateStopOrderResult.qty == null : this.qty.equals(linearCreateStopOrderResult.qty)) &&
        (this.timeInForce == null ? linearCreateStopOrderResult.timeInForce == null : this.timeInForce.equals(linearCreateStopOrderResult.timeInForce)) &&
        (this.orderStatus == null ? linearCreateStopOrderResult.orderStatus == null : this.orderStatus.equals(linearCreateStopOrderResult.orderStatus)) &&
        (this.triggerPrice == null ? linearCreateStopOrderResult.triggerPrice == null : this.triggerPrice.equals(linearCreateStopOrderResult.triggerPrice)) &&
        (this.orderLinkId == null ? linearCreateStopOrderResult.orderLinkId == null : this.orderLinkId.equals(linearCreateStopOrderResult.orderLinkId)) &&
        (this.createdAt == null ? linearCreateStopOrderResult.createdAt == null : this.createdAt.equals(linearCreateStopOrderResult.createdAt)) &&
        (this.updatedAt == null ? linearCreateStopOrderResult.updatedAt == null : this.updatedAt.equals(linearCreateStopOrderResult.updatedAt)) &&
        (this.takeProfit == null ? linearCreateStopOrderResult.takeProfit == null : this.takeProfit.equals(linearCreateStopOrderResult.takeProfit)) &&
        (this.stopLoss == null ? linearCreateStopOrderResult.stopLoss == null : this.stopLoss.equals(linearCreateStopOrderResult.stopLoss)) &&
        (this.tpTriggerBy == null ? linearCreateStopOrderResult.tpTriggerBy == null : this.tpTriggerBy.equals(linearCreateStopOrderResult.tpTriggerBy)) &&
        (this.slTriggerBy == null ? linearCreateStopOrderResult.slTriggerBy == null : this.slTriggerBy.equals(linearCreateStopOrderResult.slTriggerBy));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.stopOrderId == null ? 0: this.stopOrderId.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    result = 31 * result + (this.side == null ? 0: this.side.hashCode());
    result = 31 * result + (this.symbol == null ? 0: this.symbol.hashCode());
    result = 31 * result + (this.orderType == null ? 0: this.orderType.hashCode());
    result = 31 * result + (this.price == null ? 0: this.price.hashCode());
    result = 31 * result + (this.qty == null ? 0: this.qty.hashCode());
    result = 31 * result + (this.timeInForce == null ? 0: this.timeInForce.hashCode());
    result = 31 * result + (this.orderStatus == null ? 0: this.orderStatus.hashCode());
    result = 31 * result + (this.triggerPrice == null ? 0: this.triggerPrice.hashCode());
    result = 31 * result + (this.orderLinkId == null ? 0: this.orderLinkId.hashCode());
    result = 31 * result + (this.createdAt == null ? 0: this.createdAt.hashCode());
    result = 31 * result + (this.updatedAt == null ? 0: this.updatedAt.hashCode());
    result = 31 * result + (this.takeProfit == null ? 0: this.takeProfit.hashCode());
    result = 31 * result + (this.stopLoss == null ? 0: this.stopLoss.hashCode());
    result = 31 * result + (this.tpTriggerBy == null ? 0: this.tpTriggerBy.hashCode());
    result = 31 * result + (this.slTriggerBy == null ? 0: this.slTriggerBy.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinearCreateStopOrderResult {\n");
    
    sb.append("  stopOrderId: ").append(stopOrderId).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("  side: ").append(side).append("\n");
    sb.append("  symbol: ").append(symbol).append("\n");
    sb.append("  orderType: ").append(orderType).append("\n");
    sb.append("  price: ").append(price).append("\n");
    sb.append("  qty: ").append(qty).append("\n");
    sb.append("  timeInForce: ").append(timeInForce).append("\n");
    sb.append("  orderStatus: ").append(orderStatus).append("\n");
    sb.append("  triggerPrice: ").append(triggerPrice).append("\n");
    sb.append("  orderLinkId: ").append(orderLinkId).append("\n");
    sb.append("  createdAt: ").append(createdAt).append("\n");
    sb.append("  updatedAt: ").append(updatedAt).append("\n");
    sb.append("  takeProfit: ").append(takeProfit).append("\n");
    sb.append("  stopLoss: ").append(stopLoss).append("\n");
    sb.append("  tpTriggerBy: ").append(tpTriggerBy).append("\n");
    sb.append("  slTriggerBy: ").append(slTriggerBy).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
