//
// OrderListData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Get order list response */

public struct OrderListData: Codable {

    public var data: [OrderRes]?

    public init(data: [OrderRes]?) {
        self.data = data
    }


}

