//
// TradeRecords.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Get the trade records of a order response */

public struct TradeRecords: Codable {

    public var orderId: String?
    public var tradeList: [TradeRecordsInfo]?

    public init(orderId: String?, tradeList: [TradeRecordsInfo]?) {
        self.orderId = orderId
        self.tradeList = tradeList
    }

    public enum CodingKeys: String, CodingKey { 
        case orderId = "order_id"
        case tradeList = "trade_list"
    }


}

