//
// TradeRecordsInfo.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Get the trade records of a order response */

public struct TradeRecordsInfo: Codable {

    public var closedSize: Double?
    public var crossSeq: Double?
    public var execFee: String?
    public var execId: String?
    public var execPrice: String?
    public var execQty: Double?
    public var execTime: String?
    public var execType: String?
    public var execValue: String?
    public var feeRate: String?
    public var lastLiquidityInd: String?
    public var leavesQty: Double?
    public var nthFill: Double?
    public var orderId: String?
    public var orderPrice: String?
    public var orderQty: Double?
    public var orderType: String?
    public var side: String?
    public var symbol: String?
    public var userId: Double?

    public init(closedSize: Double?, crossSeq: Double?, execFee: String?, execId: String?, execPrice: String?, execQty: Double?, execTime: String?, execType: String?, execValue: String?, feeRate: String?, lastLiquidityInd: String?, leavesQty: Double?, nthFill: Double?, orderId: String?, orderPrice: String?, orderQty: Double?, orderType: String?, side: String?, symbol: String?, userId: Double?) {
        self.closedSize = closedSize
        self.crossSeq = crossSeq
        self.execFee = execFee
        self.execId = execId
        self.execPrice = execPrice
        self.execQty = execQty
        self.execTime = execTime
        self.execType = execType
        self.execValue = execValue
        self.feeRate = feeRate
        self.lastLiquidityInd = lastLiquidityInd
        self.leavesQty = leavesQty
        self.nthFill = nthFill
        self.orderId = orderId
        self.orderPrice = orderPrice
        self.orderQty = orderQty
        self.orderType = orderType
        self.side = side
        self.symbol = symbol
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey { 
        case closedSize = "closed_size"
        case crossSeq = "cross_seq"
        case execFee = "exec_fee"
        case execId = "exec_id"
        case execPrice = "exec_price"
        case execQty = "exec_qty"
        case execTime = "exec_time"
        case execType = "exec_type"
        case execValue = "exec_value"
        case feeRate = "fee_rate"
        case lastLiquidityInd = "last_liquidity_ind"
        case leavesQty = "leaves_qty"
        case nthFill = "nth_fill"
        case orderId = "order_id"
        case orderPrice = "order_price"
        case orderQty = "order_qty"
        case orderType = "order_type"
        case side
        case symbol
        case userId = "user_id"
    }


}

