# coding: utf-8

"""
    Bybit API

    ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]    # noqa: E501

    OpenAPI spec version: 0.2.11
    Contact: support@bybit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.set_risk_limit_base import SetRiskLimitBase  # noqa: E501
from swagger_client.rest import ApiException


class TestSetRiskLimitBase(unittest.TestCase):
    """SetRiskLimitBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetRiskLimitBase(self):
        """Test SetRiskLimitBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.set_risk_limit_base.SetRiskLimitBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
