# coding: utf-8

"""
    Bybit API

    ## REST API for the Bybit Exchange. Base URI: [https://api-testnet.bybit.com]    # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: support@bybit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.linear_conditional_api import LinearConditionalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLinearConditionalApi(unittest.TestCase):
    """LinearConditionalApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.linear_conditional_api.LinearConditionalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_linear_conditional_new(self):
        """Test case for linear_conditional_new

        Create linear stop Order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
