# coding: utf-8

"""
    Bybit API

    ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]    # noqa: E501

    OpenAPI spec version: 0.2.11
    Contact: support@bybit.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.linear_conditional_api import LinearConditionalApi  # noqa: E501
from swagger_client.rest import ApiException


class TestLinearConditionalApi(unittest.TestCase):
    """LinearConditionalApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.linear_conditional_api.LinearConditionalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_linear_conditional_cancel(self):
        """Test case for linear_conditional_cancel

        Cancel Active Order  # noqa: E501
        """
        pass

    def test_linear_conditional_cancel_all(self):
        """Test case for linear_conditional_cancel_all

        Cancel all stop orders.  # noqa: E501
        """
        pass

    def test_linear_conditional_get_orders(self):
        """Test case for linear_conditional_get_orders

        Get linear Stop Orders  # noqa: E501
        """
        pass

    def test_linear_conditional_new(self):
        """Test case for linear_conditional_new

        Create linear stop Order  # noqa: E501
        """
        pass

    def test_linear_conditional_query(self):
        """Test case for linear_conditional_query

        Get Stop Orders(real-time)  # noqa: E501
        """
        pass

    def test_linear_conditional_replace(self):
        """Test case for linear_conditional_replace

        Replace conditional order  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
