/* 
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FundRecordBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FundRecordBaseTests
    {
        // TODO uncomment below to declare an instance variable for FundRecordBase
        //private FundRecordBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FundRecordBase
            //instance = new FundRecordBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FundRecordBase
        /// </summary>
        [Test]
        public void FundRecordBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FundRecordBase
            //Assert.IsInstanceOfType<FundRecordBase> (instance, "variable 'instance' is a FundRecordBase");
        }


        /// <summary>
        /// Test the property 'RetCode'
        /// </summary>
        [Test]
        public void RetCodeTest()
        {
            // TODO unit test for the property 'RetCode'
        }
        /// <summary>
        /// Test the property 'RetMsg'
        /// </summary>
        [Test]
        public void RetMsgTest()
        {
            // TODO unit test for the property 'RetMsg'
        }
        /// <summary>
        /// Test the property 'ExtCode'
        /// </summary>
        [Test]
        public void ExtCodeTest()
        {
            // TODO unit test for the property 'ExtCode'
        }
        /// <summary>
        /// Test the property 'ExtInfo'
        /// </summary>
        [Test]
        public void ExtInfoTest()
        {
            // TODO unit test for the property 'ExtInfo'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'TimeNow'
        /// </summary>
        [Test]
        public void TimeNowTest()
        {
            // TODO unit test for the property 'TimeNow'
        }

    }

}
