/* 
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LinearRiskLimitResp
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LinearRiskLimitRespTests
    {
        // TODO uncomment below to declare an instance variable for LinearRiskLimitResp
        //private LinearRiskLimitResp instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LinearRiskLimitResp
            //instance = new LinearRiskLimitResp();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LinearRiskLimitResp
        /// </summary>
        [Test]
        public void LinearRiskLimitRespInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LinearRiskLimitResp
            //Assert.IsInstanceOfType<LinearRiskLimitResp> (instance, "variable 'instance' is a LinearRiskLimitResp");
        }


        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsLowestRisk'
        /// </summary>
        [Test]
        public void IsLowestRiskTest()
        {
            // TODO unit test for the property 'IsLowestRisk'
        }
        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Test]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
        /// <summary>
        /// Test the property 'MaintainMargin'
        /// </summary>
        [Test]
        public void MaintainMarginTest()
        {
            // TODO unit test for the property 'MaintainMargin'
        }
        /// <summary>
        /// Test the property 'Section'
        /// </summary>
        [Test]
        public void SectionTest()
        {
            // TODO unit test for the property 'Section'
        }
        /// <summary>
        /// Test the property 'StartingMargin'
        /// </summary>
        [Test]
        public void StartingMarginTest()
        {
            // TODO unit test for the property 'StartingMargin'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

    }

}
