/* 
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LinearCreateOrderResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LinearCreateOrderResultTests
    {
        // TODO uncomment below to declare an instance variable for LinearCreateOrderResult
        //private LinearCreateOrderResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LinearCreateOrderResult
            //instance = new LinearCreateOrderResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LinearCreateOrderResult
        /// </summary>
        [Test]
        public void LinearCreateOrderResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LinearCreateOrderResult
            //Assert.IsInstanceOfType<LinearCreateOrderResult> (instance, "variable 'instance' is a LinearCreateOrderResult");
        }


        /// <summary>
        /// Test the property 'CreatedTime'
        /// </summary>
        [Test]
        public void CreatedTimeTest()
        {
            // TODO unit test for the property 'CreatedTime'
        }
        /// <summary>
        /// Test the property 'CumExecFee'
        /// </summary>
        [Test]
        public void CumExecFeeTest()
        {
            // TODO unit test for the property 'CumExecFee'
        }
        /// <summary>
        /// Test the property 'CumExecQty'
        /// </summary>
        [Test]
        public void CumExecQtyTest()
        {
            // TODO unit test for the property 'CumExecQty'
        }
        /// <summary>
        /// Test the property 'CumExecValue'
        /// </summary>
        [Test]
        public void CumExecValueTest()
        {
            // TODO unit test for the property 'CumExecValue'
        }
        /// <summary>
        /// Test the property 'LastExecPrice'
        /// </summary>
        [Test]
        public void LastExecPriceTest()
        {
            // TODO unit test for the property 'LastExecPrice'
        }
        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Test]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'OrderLinkId'
        /// </summary>
        [Test]
        public void OrderLinkIdTest()
        {
            // TODO unit test for the property 'OrderLinkId'
        }
        /// <summary>
        /// Test the property 'OrderStatus'
        /// </summary>
        [Test]
        public void OrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatus'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Test]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Qty'
        /// </summary>
        [Test]
        public void QtyTest()
        {
            // TODO unit test for the property 'Qty'
        }
        /// <summary>
        /// Test the property 'ReduceOnly'
        /// </summary>
        [Test]
        public void ReduceOnlyTest()
        {
            // TODO unit test for the property 'ReduceOnly'
        }
        /// <summary>
        /// Test the property 'Side'
        /// </summary>
        [Test]
        public void SideTest()
        {
            // TODO unit test for the property 'Side'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'TimeInForce'
        /// </summary>
        [Test]
        public void TimeInForceTest()
        {
            // TODO unit test for the property 'TimeInForce'
        }
        /// <summary>
        /// Test the property 'UpdatedTime'
        /// </summary>
        [Test]
        public void UpdatedTimeTest()
        {
            // TODO unit test for the property 'UpdatedTime'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'TakeProfit'
        /// </summary>
        [Test]
        public void TakeProfitTest()
        {
            // TODO unit test for the property 'TakeProfit'
        }
        /// <summary>
        /// Test the property 'StopLoss'
        /// </summary>
        [Test]
        public void StopLossTest()
        {
            // TODO unit test for the property 'StopLoss'
        }
        /// <summary>
        /// Test the property 'TpTriggerBy'
        /// </summary>
        [Test]
        public void TpTriggerByTest()
        {
            // TODO unit test for the property 'TpTriggerBy'
        }
        /// <summary>
        /// Test the property 'SlTriggerBy'
        /// </summary>
        [Test]
        public void SlTriggerByTest()
        {
            // TODO unit test for the property 'SlTriggerBy'
        }

    }

}
