/* 
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OpenInterestInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OpenInterestInfoTests
    {
        // TODO uncomment below to declare an instance variable for OpenInterestInfo
        //private OpenInterestInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OpenInterestInfo
            //instance = new OpenInterestInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OpenInterestInfo
        /// </summary>
        [Test]
        public void OpenInterestInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OpenInterestInfo
            //Assert.IsInstanceOfType<OpenInterestInfo> (instance, "variable 'instance' is a OpenInterestInfo");
        }


        /// <summary>
        /// Test the property 'OpenInterest'
        /// </summary>
        [Test]
        public void OpenInterestTest()
        {
            // TODO unit test for the property 'OpenInterest'
        }
        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Test]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Test]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }

    }

}
