/* 
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing WalletBalance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WalletBalanceTests
    {
        // TODO uncomment below to declare an instance variable for WalletBalance
        //private WalletBalance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WalletBalance
            //instance = new WalletBalance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WalletBalance
        /// </summary>
        [Test]
        public void WalletBalanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WalletBalance
            //Assert.IsInstanceOfType<WalletBalance> (instance, "variable 'instance' is a WalletBalance");
        }


        /// <summary>
        /// Test the property 'Equity'
        /// </summary>
        [Test]
        public void EquityTest()
        {
            // TODO unit test for the property 'Equity'
        }
        /// <summary>
        /// Test the property 'AvailableBalance'
        /// </summary>
        [Test]
        public void AvailableBalanceTest()
        {
            // TODO unit test for the property 'AvailableBalance'
        }
        /// <summary>
        /// Test the property 'UsedMargin'
        /// </summary>
        [Test]
        public void UsedMarginTest()
        {
            // TODO unit test for the property 'UsedMargin'
        }
        /// <summary>
        /// Test the property 'OrderMargin'
        /// </summary>
        [Test]
        public void OrderMarginTest()
        {
            // TODO unit test for the property 'OrderMargin'
        }
        /// <summary>
        /// Test the property 'PositionMargin'
        /// </summary>
        [Test]
        public void PositionMarginTest()
        {
            // TODO unit test for the property 'PositionMargin'
        }
        /// <summary>
        /// Test the property 'OccClosingFee'
        /// </summary>
        [Test]
        public void OccClosingFeeTest()
        {
            // TODO unit test for the property 'OccClosingFee'
        }
        /// <summary>
        /// Test the property 'OccFundingFee'
        /// </summary>
        [Test]
        public void OccFundingFeeTest()
        {
            // TODO unit test for the property 'OccFundingFee'
        }
        /// <summary>
        /// Test the property '_WalletBalance'
        /// </summary>
        [Test]
        public void _WalletBalanceTest()
        {
            // TODO unit test for the property '_WalletBalance'
        }
        /// <summary>
        /// Test the property 'RealisedPnl'
        /// </summary>
        [Test]
        public void RealisedPnlTest()
        {
            // TODO unit test for the property 'RealisedPnl'
        }
        /// <summary>
        /// Test the property 'UnrealisedPnl'
        /// </summary>
        [Test]
        public void UnrealisedPnlTest()
        {
            // TODO unit test for the property 'UnrealisedPnl'
        }
        /// <summary>
        /// Test the property 'CumRealisedPnl'
        /// </summary>
        [Test]
        public void CumRealisedPnlTest()
        {
            // TODO unit test for the property 'CumRealisedPnl'
        }
        /// <summary>
        /// Test the property 'GivenCash'
        /// </summary>
        [Test]
        public void GivenCashTest()
        {
            // TODO unit test for the property 'GivenCash'
        }
        /// <summary>
        /// Test the property 'ServiceCash'
        /// </summary>
        [Test]
        public void ServiceCashTest()
        {
            // TODO unit test for the property 'ServiceCash'
        }

    }

}
