<?php
/**
 * ConditionalCancelAllResTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bybit API
 *
 * ## REST API for the Bybit Exchange. Base URI: [https://api-testnet.bybit.com]
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bybit.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConditionalCancelAllResTest Class Doc Comment
 *
 * @category    Class
 * @description Cancel all conditional order response
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConditionalCancelAllResTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConditionalCancelAllRes"
     */
    public function testConditionalCancelAllRes()
    {
    }

    /**
     * Test attribute "cl_ord_id"
     */
    public function testPropertyClOrdId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "symbol"
     */
    public function testPropertySymbol()
    {
    }

    /**
     * Test attribute "side"
     */
    public function testPropertySide()
    {
    }

    /**
     * Test attribute "order_type"
     */
    public function testPropertyOrderType()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "qty"
     */
    public function testPropertyQty()
    {
    }

    /**
     * Test attribute "time_in_force"
     */
    public function testPropertyTimeInForce()
    {
    }

    /**
     * Test attribute "create_type"
     */
    public function testPropertyCreateType()
    {
    }

    /**
     * Test attribute "cancel_type"
     */
    public function testPropertyCancelType()
    {
    }

    /**
     * Test attribute "order_status"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "leaves_qty"
     */
    public function testPropertyLeavesQty()
    {
    }

    /**
     * Test attribute "leaves_value"
     */
    public function testPropertyLeavesValue()
    {
    }

    /**
     * Test attribute "cross_seq"
     */
    public function testPropertyCrossSeq()
    {
    }

    /**
     * Test attribute "stop_order_type"
     */
    public function testPropertyStopOrderType()
    {
    }

    /**
     * Test attribute "trigger_by"
     */
    public function testPropertyTriggerBy()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }
}
