/*
 * Bybit API
 * ## REST API for the Bybit Exchange. Base URI: [https://api.bybit.com]  
 *
 * OpenAPI spec version: 0.2.10
 * Contact: support@bybit.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Cancel Linear Stop Order
 */
@ApiModel(description = "Cancel Linear Stop Order")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-11-12T14:39:31.513+08:00")
public class LinearCancelStopOrderResult {
  @SerializedName("stop_order_id")
  private String stopOrderId = null;

  public LinearCancelStopOrderResult stopOrderId(String stopOrderId) {
    this.stopOrderId = stopOrderId;
    return this;
  }

   /**
   * Get stopOrderId
   * @return stopOrderId
  **/
  @ApiModelProperty(value = "")
  public String getStopOrderId() {
    return stopOrderId;
  }

  public void setStopOrderId(String stopOrderId) {
    this.stopOrderId = stopOrderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LinearCancelStopOrderResult linearCancelStopOrderResult = (LinearCancelStopOrderResult) o;
    return Objects.equals(this.stopOrderId, linearCancelStopOrderResult.stopOrderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stopOrderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LinearCancelStopOrderResult {\n");
    
    sb.append("    stopOrderId: ").append(toIndentedString(stopOrderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

