//
// LinearFundingAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class LinearFundingAPI {
    /**
     Get prev funding
     
     - parameter symbol: (query)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func linearFundingMyLastFee(symbol: String? = nil, completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        linearFundingMyLastFeeWithRequestBuilder(symbol: symbol).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get prev funding
     - GET /private/linear/funding/prev-funding
     - This will get prev funding
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apiKey
     - API Key:
       - type: apiKey sign (QUERY)
       - name: apiSignature
     - API Key:
       - type: apiKey timestamp (QUERY)
       - name: timestamp
     - examples: [{contentType=application/json, example=""}]
     
     - parameter symbol: (query)  (optional)

     - returns: RequestBuilder<Any> 
     */
    open class func linearFundingMyLastFeeWithRequestBuilder(symbol: String? = nil) -> RequestBuilder<Any> {
        let path = "/private/linear/funding/prev-funding"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "symbol": symbol
        ])

        let requestBuilder: RequestBuilder<Any>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get predicted funding rate and funding fee.
     
     - parameter symbol: (query) Contract type. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func linearFundingPredicted(symbol: String, completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        linearFundingPredictedWithRequestBuilder(symbol: symbol).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get predicted funding rate and funding fee.
     - GET /private/linear/funding/predicted-funding
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apiKey
     - API Key:
       - type: apiKey sign (QUERY)
       - name: apiSignature
     - API Key:
       - type: apiKey timestamp (QUERY)
       - name: timestamp
     - examples: [{contentType=application/json, example=""}]
     
     - parameter symbol: (query) Contract type. 

     - returns: RequestBuilder<Any> 
     */
    open class func linearFundingPredictedWithRequestBuilder(symbol: String) -> RequestBuilder<Any> {
        let path = "/private/linear/funding/predicted-funding"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "symbol": symbol
        ])

        let requestBuilder: RequestBuilder<Any>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     Get prev funding
     
     - parameter symbol: (query)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func linearFundingPrevRate(symbol: String, completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        linearFundingPrevRateWithRequestBuilder(symbol: symbol).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get prev funding
     - GET /public/linear/funding/prev-funding-rate
     - This will get prev funding rate
     - API Key:
       - type: apiKey api_key (QUERY)
       - name: apiKey
     - API Key:
       - type: apiKey sign (QUERY)
       - name: apiSignature
     - API Key:
       - type: apiKey timestamp (QUERY)
       - name: timestamp
     - examples: [{contentType=application/json, example=""}]
     
     - parameter symbol: (query)  

     - returns: RequestBuilder<Any> 
     */
    open class func linearFundingPrevRateWithRequestBuilder(symbol: String) -> RequestBuilder<Any> {
        let path = "/public/linear/funding/prev-funding-rate"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "symbol": symbol
        ])

        let requestBuilder: RequestBuilder<Any>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
